### ISSUE TITLE
lein-tools-deps issue

### ISSUE THREAD

**Issue by NoahTheDuke** [pangloss/pure-conditioning#1]
Hey there!

It seems that [lein-tools-deps](https://github.com/RickMoynihan/lein-tools-deps) no longer works with recent versions of tools.deps. Do you have any suggestions on how to run tests?

**Comment by pangloss** [comment]
Hmm, I think this was the first project that I used tools deps on. Pushed a trivial fix so that you can use `clojure -Mtest`

**Comment by NoahTheDuke** [comment]
Thank you!
